version: 2

build:
   os: ubuntu-lts-latest
   tools:
      python: "3.13"
   jobs:
      create_environment:
         - asdf plugin add uv
         - asdf install uv latest
         - asdf global uv latest
         - uv venv
      install:
         - uv sync --locked --no-dev --all-extras
         - uv pip install Sphinx
      build:
         html:
            - uv run sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
