# Generated by Django 2.0.3 on 2018-03-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=64, verbose_name='Last name')),
                ('country', models.CharField(choices=[('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy')], max_length=32, verbose_name='Country')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Birthdate')),
                ('reminder', models.DateTimeField(verbose_name='Next reminder')),
                ('approved', models.BooleanField(verbose_name='Is approved')),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Stars')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
    ]
