# Generated by Django 2.0.3 on 2018-04-25 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=64, verbose_name='Last name'),
                ),
                (
                    'country',
                    models.CharField(
                        choices=[
                            ('Germany', 'Germany'),
                            ('France', 'France'),
                            ('Italy', 'Italy'),
                        ],
                        max_length=32,
                        verbose_name='Country',
                    ),
                ),
                (
                    'birthdate',
                    models.DateField(blank=True, null=True, verbose_name='Birthdate'),
                ),
                ('reminder', models.DateTimeField(verbose_name='Next reminder')),
                ('approved', models.BooleanField(verbose_name='Is approved')),
                (
                    'stars',
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Stars'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='RelatedPerson',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('first_name', models.CharField(max_length=64, verbose_name='First name')),
                (
                    'last_name',
                    models.CharField(blank=True, max_length=64, verbose_name='Last name'),
                ),
                ('is_child', models.BooleanField(verbose_name='Is child')),
                (
                    'person',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='store.Person'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Related person',
                'verbose_name_plural': 'Related persons',
            },
        ),
    ]
