name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    name: "Upload to PyPI"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - uses: "astral-sh/setup-uv@v5"
      - run: "uv build"
      - run: "uv publish"
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
